### ISSUE TITLE
Tradução portuguesa

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/LibQuestData#12]
NOTA: Se não houver nenhum incidente do GitHub aberto, não traduza a modificação. O autor não está trabalhando comigo e pode não aceitar a tradução. Mais para minhas mudanças pessoais.

- [x] Nomes de missão
- [ ] Nomes de NPC (personagem não-jogador) - ( opcional )

A tradução dos nomes NPC é opcional porque apenas destinos os usa e há uma opção para desabilitar os nomes NPC. Além disso, torna o nome do título da missão mais longo.

É melhor agora, não faça isso até que haja uma maneira melhor do que usando LibQuestData.

**Comment by Sharlikran** [comment]
@Telmatoscopus Alguém me contatou na ESOUI chamado mlsevero e se ofereceu para ajudar na tradução. Talvez vocês dois possam trabalhar juntos.

**Comment by Sharlikran** [comment]
@mlsevero Isso parece maravilhoso. Obrigado por isso.

Vou perder a internet em alguns dias. As atualizações terão que esperar até que você tenha internet novamente.

No entanto, você pode traduzir arquivos e anexar os arquivos zip no GitHub enquanto eu não tenho internet.

**Comment by Sharlikran** [comment]
@mlsevero try the current version and see how that work

**Comment by mlsevero** [comment]
Congratulations...


Em 18 de outubro de 2022, à(s) 01:51, Sharlikran ***@***.***> escreveu:


Closed #12<https://github.com/ESOUIMods/LibQuestData/issues/12> as completed.
