### ISSUE TITLE
get_measurement_sv: attempt to index a nil value

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/LibQuestData#2]
```Lua
user:/AddOns/LibQuestInfo/LibQuestInfo_Scan.lua:39: attempt to index a nil value
stack traceback:
user:/AddOns/LibQuestInfo/LibQuestInfo_Scan.lua:39: in function 'get_measurement_sv'
|caaaaaa
<Locals> zone = "Art/maps/auridon/auridon_base_..." 
</Locals>|r user:/AddOns/LibQuestInfo/LibQuestInfo_Scan.lua:176: in function 'OnQuestAdded'
|caaaaaa
<Locals> eventCode = 131079, journalIndex = 3, questName = "Real Marines", objectiveName = "Silsailen", quest_type = 0, repeat_type = 0, quest_id = -1, zone = "auridon/auridon_base_0",
normalizedX = 0.63192754983902, normalizedY = 0.8261930346489, gpsx = 0.23702440708891, gpsy = 0.72734639555171, zoneMapIndex = 15, 
measurement = [table:1]{zoneId = 381, mapIndex = 15, scaleX = 0.15792002441846, offsetX = 0.13723039298763, offsetY = 0.59687399194678, id = "Art/maps/auridon/auridon_base_...", scaleY = 0.15791999948339}, 
quest = [table:2]{gpsy = 0.72734639555171, objective = "Silsailen", lang = "en", giver = "Hanilan", api = 100030, name = "Real Marines", repeat_type = 0, questID = -1, x = 0.63192754983902, y = 0.8261930346489, quest_type = 0, gpsx = 0.23702440708891}, 
measurement_info = [table:3]{offsetY = 0.59687399194678, mapIndex = 15, scaleX = 0.15792002441846, offsetX = 0.13723039298763, zoneId = 381, scaleY = 0.15791999948339} 
</Locals>|r
```

**Comment by trowieuk** [comment]
[LibQuestInfo.zip](https://github.com/ESOUIMods/LibQuestInfo/files/4672529/LibQuestInfo.zip)

**Comment by Sharlikran** [comment]
## Dan at ZOS

If all were working as intended, anyone with the above `LibQuestInfo.lua` file from the user `trowieuk` would have the following file after accepting a few quests in Greymoor.  For example I chose Reinforcement for Kyne's Aegis and The Gathering Storm.

[LibQuestInfo.zip](https://github.com/ESOUIMods/LibQuestInfo/files/4684754/LibQuestInfo.zip)

The new information will be under `["skyrim/westernskryim_base_0"]` and the other empty tables. When users report errors about ESO trying to access a nil value it is because the table `["map_info"]` is missing for example. However, as you can see in 

The above error was from the file from trowieuk, not only are all the other tables missing and the version is still 2 and not 4.

**Comment by Sharlikran** [comment]
[LibQuestInfo.zip](https://github.com/ESOUIMods/LibQuestInfo/files/4689400/LibQuestInfo.zip)

![image](https://user-images.githubusercontent.com/1912426/83035081-dfdba200-9fed-11ea-8bf4-c2f38b434a40.png)

So the file has been set to read only. No cloud services are monitoring the folder that could have inadvertently set that. The only thing he runs over windows is Malwarebytes.

**Comment by Sharlikran** [comment]
Doesn't seem to be happening anymore and there there has been too many updates to know why this was happening.
