### ISSUE TITLE
Quest name request 6836

### ISSUE THREAD

**Issue by jrposada** [ESOUIMods/LibQuestData#20]
## Summary
Quest name for id 6836 (Pledge: Earthen Root Enclave) is missing.

ESOUI Data: http://esoitem.uesp.net/viewlog.php?action=view&record=uniqueQuest&id=539302

Thanks for the awesome lib!

**Comment by Sharlikran** [comment]
@jrposada LibQuestData, Quest Map, and Destinations no longer use quest names files. This comes from the game itself. I keep the files for other reasons. So there is no need to make a request to add that.

**Comment by Sharlikran** [comment]
If there are any quests missing then I would need the information posted in #22 but I will be asking for specific data. Details are in the description.
