### ISSUE TITLE
Update 40 - API101040: Constants change InstanceDisplayType -> ZoneDisplayType 

### ISSUE THREAD

**Issue by Baertram** [ESOUIMods/LibQuestData#23]
Hi there,

with update U40 currently on PTS the constant InstanceDisplayType enums are replaced by ZoneDisplayType enums:

```
*** Removed ***

h5. InstanceDisplayType
* INSTANCE_DISPLAY_TYPE_BATTLEGROUND
* INSTANCE_DISPLAY_TYPE_COMPANION
* INSTANCE_DISPLAY_TYPE_DELVE
* INSTANCE_DISPLAY_TYPE_DUNGEON
* INSTANCE_DISPLAY_TYPE_GROUP_AREA
* INSTANCE_DISPLAY_TYPE_GROUP_DELVE
* INSTANCE_DISPLAY_TYPE_HOUSING
* INSTANCE_DISPLAY_TYPE_NONE
* INSTANCE_DISPLAY_TYPE_PUBLIC_DUNGEON
* INSTANCE_DISPLAY_TYPE_RAID
* INSTANCE_DISPLAY_TYPE_SOLO
* INSTANCE_DISPLAY_TYPE_ZONE_STORY

```

```
*** ADDED *** 

h5. ZoneDisplayType
* ZONE_DISPLAY_TYPE_BATTLEGROUND
* ZONE_DISPLAY_TYPE_COMPANION
* ZONE_DISPLAY_TYPE_DELVE
* ZONE_DISPLAY_TYPE_DUNGEON
* ZONE_DISPLAY_TYPE_ENDLESS_DUNGEON
* ZONE_DISPLAY_TYPE_GROUP_AREA
* ZONE_DISPLAY_TYPE_GROUP_DELVE
* ZONE_DISPLAY_TYPE_HOUSING
* ZONE_DISPLAY_TYPE_NONE
* ZONE_DISPLAY_TYPE_PUBLIC_DUNGEON
* ZONE_DISPLAY_TYPE_RAID
* ZONE_DISPLAY_TYPE_SOLO
* ZONE_DISPLAY_TYPE_ZONE_STORY

```
[APIPatchNotesP40.txt](https://github.com/ESOUIMods/LibQuestData/files/12703048/APIPatchNotesP40.txt)

Relating API function GetJournalQuestInfo changes too:
* GetJournalQuestInfo(*luaindex* _journalQuestIndex_)
** _Returns:_ *string* _questName_, *string* _backgroundText_, *string* _activeStepText_, *integer* _activeStepType_, *string* _activeStepTrackerOverrideText_, *bool* _completed_, *bool* _tracked_, *integer* _questLevel_, *bool* _pushed_, *integer* _questType_, *[ZoneDisplayType|#ZoneDisplayType]* _zoneDisplayType_

And a new API function got added:
* GetJournalQuestZoneDisplayType(*luaindex* _journalQuestIndex_)
** _Returns:_ *[ZoneDisplayType|#ZoneDisplayType]* _zoneDisplayType_

Events changed:
* EVENT_QUEST_COMPLETE (*string* _questName_, *integer* _level_, *integer* _previousExperience_, *integer* _currentExperience_, *integer* _championPoints_, *[QuestType|#QuestType]* _questType_, *[ZoneDisplayType|#ZoneDisplayType]* _zoneDisplayType_)

**Comment by Sharlikran** [comment]
Thanks for that but I don't use those functions or that event. Although I may see if other changes to U40 would be helpful.
