### ISSUE TITLE
Quest Missing From Lib

### ISSUE THREAD

**Issue by potasium56** [ESOUIMods/LibQuestData#5]
Hello wasn't sure where to provide you with this information, would have made a pull request if I was good enough with lua but only really know javascript and some c# so probably would take me longer to figure out how to add this missing quest in your lib with code so decided to just tell you the quest name, and the x and y coordinates here and let you do all the programming. If you prefer a better place to inform you of missing quests then link me and will contact you their if i stumble across anymore.

Zone: Betnikh
Quest Npc Location: X: 112218 Y: 139047  (These coordinates are from the addon CoordsAndHeading )
Quest Name: Farsight

I think your the owner of the addon Quest Map? and this ques wasn't showing on the map as a pin

**Comment by Sharlikran** [comment]
@potasium56 I Found that this quest can be obtained at any of the three shrines. So there are multiple locations. Never the less, I have found all three places you can obtain the quest and it will be in the next version.

Thanks, and as mentioned using mods to get XY locations won't work, LibQuestData tracks the quests itself.
