### ISSUE TITLE
Przetłumacz polski

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/LibQuestData#8]
UWAGA: Jeśli nie ma otwartego incydentu GitHub, nie tłumacz modyfikacji. Autor nie pracuje ze mną i może nie przyjąć tłumaczenia. Więcej dla moich osobistych zmian.

- [ ] Tłumaczenie misji
- [ ] Nazwy NPC (postać niebędąca graczem)

**Comment by tomkolp** [comment]
Ok

**Comment by Sharlikran** [comment]
Dzięki za tłumaczenia. Sprawdź, czy wszystko działa poprawnie, a jeśli nie, daj mi znać.

**Comment by Sharlikran** [comment]
@tomkolp Dzięki za tłumaczenia. Sprawdź, czy wszystko działa poprawnie, a jeśli nie, daj mi znać.

**Comment by tomkolp** [comment]
#19 dodałem aktualizację @Sharlikran
